package com.example.ui

object Localization {
    fun get(key: String, lang: String): String {
        val faMap = mapOf(
            "title" to "پروکسی‌یاب حرفه‌ای MTProto",
            "settings_menu" to "منوی تنظیمات",
            "add_proxy" to "افزودن پروکسی (دستی/گروهی)",
            "clear_all" to "پاک‌سازی کامل لیست",
            "support" to "ارتباط با سازنده / کانال پشتیبانی",
            "change_lang" to "تغییر زبان برنامه",
            "get_proxies" to "دریافت پروکسی",
            "test_speed" to "تست سرعت",
            "active_found" to "پروکسی آنلاین یافت شد",
            "fast_subtitle" to "پروکسی‌های آنلاین با کمترین تأخیر",
            "stable_subtitle" to "پروکسی‌های دامنه‌دار (با ثبات بالا)",
            "fastest_tab" to "سریع‌ترین‌ها",
            "stable_tab" to "پایدارترین‌ها",
            "add_new_title" to "افزودن پروکسی جدید",
            "single_tab" to "تک پروکسی (دستی)",
            "bulk_tab" to "گروهی (سایت/متن)",
            "server_placeholder" to "سرور (domain or IP)",
            "bulk_placeholder" to "لینک پروکسی یا متن حاوی پروکسی‌ها را وارد کنید",
            "add" to "افزودن",
            "cancel" to "لغو",
            "clear_title" to "پاک‌سازی کامل لیست",
            "clear_confirm_text" to "آیا مطمئن هستید که می‌خواهید تمامی پروکسی‌ها را حذف کنید؟",
            "delete" to "حذف",
            "about_title" to "درباره سازنده و برنامه",
            "about_text" to "این برنامه جهت سنجش و ارزیابی پینگ و پایداری پروکسی‌های MTProto برای تلگرام طراحی شده است.",
            "contact_creator" to "ارتباط با سازنده در تلگرام",
            "telegram_channel" to "کانال رسمی تلگرام",
            "github_page" to "صفحه گیت‌هاب سازنده",
            "select_lang" to "انتخاب زبان برنامه",
            "ping_label" to "پینگ:",
            "online" to "آنلاین",
            "offline" to "آفلاین",
            "connect" to "اتصال",
            "source_label" to "منبع:",
            "source_manual" to "دستی",
            "source_github" to "گیت‌هاب",
            "delete_proxy_title" to "حذف پروکسی",
            "delete_proxy_text" to "آیا مایل به حذف این پروکسی هستید؟",
            "empty_text" to "پروکسی فعال یافت نشد. دکمه دریافت پروکسی را بزنید تا پروکسی‌ها از گیت‌هاب دریافت و تست شوند.",
            "close" to "بستن",
            "theme_toggle" to "تغییر پوسته",
            "testing_running" to "در حال تست پینگ... ",
            "overall_stability" to "پایداری کلی",
            "active_proxies" to "فعال",
            "avg_ping" to "میانگین پینگ"
        )

        val enMap = mapOf(
            "title" to "MTProto Professional Proxy Finder",
            "settings_menu" to "Settings Menu",
            "add_proxy" to "Add Proxy (Manual/Bulk)",
            "clear_all" to "Clear All Proxies",
            "support" to "Contact Creator / Support Channel",
            "change_lang" to "Change App Language",
            "get_proxies" to "Get Proxies",
            "test_speed" to "Test Speed",
            "active_found" to "online proxies found",
            "fast_subtitle" to "Online proxies with lowest latency",
            "stable_subtitle" to "Domain-based (High Stability)",
            "fastest_tab" to "Fastest",
            "stable_tab" to "Most Stable",
            "add_new_title" to "Add New Proxy",
            "single_tab" to "Single Proxy (Manual)",
            "bulk_tab" to "Bulk Import (Text/Links)",
            "server_placeholder" to "Server (domain or IP)",
            "bulk_placeholder" to "Enter proxy link or text containing proxies",
            "add" to "Add",
            "cancel" to "Cancel",
            "clear_title" to "Clear All Proxies",
            "clear_confirm_text" to "Are you sure you want to delete all proxies from the database?",
            "delete" to "Delete",
            "about_title" to "About Creator & App",
            "about_text" to "This application is designed for checking and evaluating the ping and stability of MTProto proxies for Telegram.",
            "contact_creator" to "Contact Creator on Telegram",
            "telegram_channel" to "Official Telegram Channel",
            "github_page" to "Creator's GitHub Page",
            "select_lang" to "Select App Language",
            "ping_label" to "Ping:",
            "online" to "Online",
            "offline" to "Offline",
            "connect" to "Connect",
            "source_label" to "Source:",
            "source_manual" to "Manual",
            "source_github" to "GitHub",
            "delete_proxy_title" to "Delete Proxy",
            "delete_proxy_text" to "Are you sure you want to delete this proxy?",
            "empty_text" to "No active proxies found. Tap Get Proxies to fetch from GitHub and test them.",
            "close" to "Close",
            "theme_toggle" to "Change Theme",
            "testing_running" to "Testing ping... ",
            "overall_stability" to "Overall Stability",
            "active_proxies" to "Active",
            "avg_ping" to "Avg Ping"
        )

        val ruMap = mapOf(
            "title" to "Профессиональный Поиск Прокси",
            "settings_menu" to "Меню настроек",
            "add_proxy" to "Добавить прокси (Вручную/Пакетно)",
            "clear_all" to "Очистить список прокси",
            "support" to "Контакты создателя / Канал поддержки",
            "change_lang" to "Изменить язык приложения",
            "get_proxies" to "Получить прокси",
            "test_speed" to "Тест скорости",
            "active_found" to "онлайн-прокси найдено",
            "fast_subtitle" to "Онлайн-прокси с наименьшей задержкой",
            "stable_subtitle" to "Доменные прокси (Высокая стабильность)",
            "fastest_tab" to "Быстрые",
            "stable_tab" to "Стабильные",
            "add_new_title" to "Добавить новый прокси",
            "single_tab" to "Один прокси (Вручную)",
            "bulk_tab" to "Пакетный импорт (Текст/Ссылки)",
            "server_placeholder" to "Сервер (домен или IP)",
            "bulk_placeholder" to "Введите ссылку на прокси или текст с прокси",
            "add" to "Добавить",
            "cancel" to "Отмена",
            "clear_title" to "Очистить все прокси",
            "clear_confirm_text" to "Вы уверены, что хотите удалить все прокси из базы данных?",
            "delete" to "Удалить",
            "about_title" to "О создателе и приложении",
            "about_text" to "Это приложение предназначено для проверки и оценки пинга и стабильности MTProto-прокси для Telegram.",
            "contact_creator" to "Связаться с разработчиком в Telegram",
            "telegram_channel" to "Официальный Telegram-канал",
            "github_page" to "GitHub-страница разработчика",
            "select_lang" to "Выбор языка приложения",
            "ping_label" to "Пинг:",
            "online" to "Онлайн",
            "offline" to "Офлайн",
            "connect" to "Подключить",
            "source_label" to "Источник:",
            "source_manual" to "Вручную",
            "source_github" to "GitHub",
            "delete_proxy_title" to "Удалить прокси",
            "delete_proxy_text" to "Вы действительно хотите удалить этот прокси?",
            "empty_text" to "Активные прокси не найдены. Нажмите 'Получить прокси', чтобы скачать их с GitHub и протестировать.",
            "close" to "Закрыть",
            "theme_toggle" to "Изменить тему",
            "testing_running" to "Тестирование пинга... ",
            "overall_stability" to "Стабильность",
            "active_proxies" to "Активные",
            "avg_ping" to "Средний пинг"
        )

        return when (lang) {
            "en" -> enMap[key] ?: key
            "ru" -> ruMap[key] ?: key
            else -> faMap[key] ?: key
        }
    }
}
